name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine tag
        id: tag
        env:
          VERSION: ${{ github.event.inputs.version || '' }}
        run: |
          git fetch --tags
          if [ -n "$VERSION" ]; then
            TAG="$VERSION"
            if git rev-parse "$TAG" >/dev/null 2>&1; then
              echo "Tag $TAG already exists. Skipping tag creation."
            else
              git tag "$TAG"
              git push origin "$TAG"
            fi
          else
            TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.tag.outputs.tag }}" --generate-notes --title "${{ steps.tag.outputs.tag }}"
